### ISSUE TITLE
How do you import pouchdb plugins?

### ISSUE THREAD

**Issue by dreamofi** [ArnoSaine/react-pouchdb#12]
Hello, I want to import pouchdb plugins such as pouchdb-replication-stream, how do I do it with react-pouchdb?

I tried doing this, but it does not work:
```
import PouchDb from 'pouchdb';
import {PouchDb as PouchDbComponent} from "react-pouch";

PouchDb.plugin(replicationStream.plugin);
```

**Comment by ArnoSaine** [comment]
Hi, that is the correct way to use plugins. Internally the package uses `pouchdb-find` plugin like this:
```js
import PouchDB from 'pouchdb';
import find from 'pouchdb-find';

PouchDB.plugin(find);
```

Can you make sure there is only one version of `pouchdb` anywhere in node_modules? Plugins should be added to the sibling `pouchdb` package of `react-pouchdb`. Or if you add plugins to `pouchdb-browser`, import react-pouchdb from `react-pouchdb/browser`.

**Comment by dreamofi** [comment]
@ArnoSaine Thank you for your clarification. After checking, the plugin (pouchdb-replication-stream) was indeed imported properly from my end. Initially, I tried to use the dump() function of the plugin with streamsaver directly, but it seems that the way I implemented it was incorrect, so it does not work.
