### ISSUE TITLE
Error thrown during hot reload

### ISSUE THREAD

**Issue by wolfgang42** [ArnoSaine/react-pouchdb#2]
I'm using react-pouchdb in a project that has hot module reloading enabled. When the components reload, I get a DOMException "A mutation operation was attempted on a database that did not allow mutations." (and no documents are returned from `<Find>`).

This looks like some sort of problem with PouchDB having closed the IndexedDB, though I don't know enough about any of the pieces involved to be able to identify the exact cause or how to fix it.

**Comment by ArnoSaine** [comment]
Thank you for reporting this issue.

It seems that closing and immediately opening the db causes the error. I updated the package. PouchDB connections are now pooled by the name and other options. Remount of a component no longer closes the connection at least in my test app. Please check if you get the error with the latest version?

**Comment by wolfgang42** [comment]
Yes, hot reloading is now working correctly with react-pouchdb@0.1.4. Thank you for the quick fix, and for your work on this library! It's been indispensable for quickly writing an interface to a PouchDB database.
