### ISSUE TITLE
MaxListenersExceededWarning with only one useFind and two useGets

### ISSUE THREAD

**Issue by rbhalla** [ArnoSaine/react-pouchdb#22]
Hi,

First off, thank you for this library. It's exactly what I was looking for.

I've tried to build a simple test of it that replicates a remote db.

To do the replication, in my root component I have something like this:

```
  const db = useDB();

  useEffect(() => {
    db.sync(new PouchDB(config.dbURL + '/mydb'), {
      live: true,
      retry: true,
    });
  }, []);
```

That seems to be working well, and it initialises the sync once. I am not sure if there was a better way to do this (have a local db synced with a remote) so please tell me if this is what is affecting it.

I then built two pages, one that uses `useFind` to get a list of items. And another that uses `useGet` to get a specific item when you click on it.

Right now, if I go to the page that shows everything, click an item, click back, then click another item, I would expect only 3 things to have been queried (list and 2 items), with only 3 event listeners, but I get this error:

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
```

I'm not sure how it got to 11 listeners, nor why it is failing so quickly. My list only has 3 things in it, so I can't think of any other way it got to 11.

Are you able to see something I haven't?

EDIT: This actually only seems to be happening when I setup the sync. Is there a recommended way to sync the local db with a remote that would avoid this problem?

**Comment by ArnoSaine** [comment]
Hi,

glad you find this library useful!

That is how I'd sync local and remote databases. I don't know what's wrong.

I haven't used sync, but I do get MaxListenersExceededWarning quite easily and find it also strange. The amount of listeners seems to stay in certain range while an app is used, so I have just decided to increase the value of `maxListeners`.

**Comment by rbhalla** [comment]
That's strange. I've noticed it doesn't actually affect my application and everything stays in sync with the remote db. When I inspect the individual PouchDB instances, none of them register as having listeners at all (another oddity)
It's possibly something I can ignore for now. 

Out of curiosity, I am going to guess the default is low for a particular reason. Is there something I should consider when increasing it?

I also appreciate this might not be related to the library like I thought and may be more related to PouchDB itself, so feel free to close this issue if it's not useful to keep around.

**Comment by ArnoSaine** [comment]
Yeah, the default is low so that memory leaks would be detected early. Increasing it is fine, if the reason is not a memory leak. I think it isn't a memory leak, as the amount of listeners don't keep growing while the app is used.
