### ISSUE TITLE
Multiple DBs

### ISSUE THREAD

**Issue by bkniffler** [ArnoSaine/react-pouchdb#4]
Heya, 
Most apps will have multiple databases (as in multiple collections). Currently you can only provide a single database.

Something like this would be awesome:
```jsx
<Find db="users" selector={...} />
```

**Comment by ArnoSaine** [comment]
This is now available in [1.0.0-alpha.0](https://www.npmjs.com/package/react-pouchdb/v/1.0.0-alpha.0) along with new hooks API.

**Comment by kn0ll** [comment]
came back to check for multiple dbs... got hooks too! awesome, thanks!
