### ISSUE TITLE
API Variants: Synchronous , not working as expected

### ISSUE THREAD

**Issue by MiLaDTechS** [ArnoSaine/react-pouchdb#44]
According to docs :

<pre>
Synchronous
It is guaranteed that the API returns with a final response value from PouchDB. Because of this, requests are made sequentially.

Import from react-pouchdb to use the Synchronous API. Example:

import { useFind, useDB } from "react-pouchdb";
</pre>

but it errors if used without react suspense

**Comment by ArnoSaine** [comment]
Sorry about the misconception. Suspense is required to use this API, as PouchDB is async. Synchronous in this case means React handles the loading state, and the API user is free to use the eventual response value from the DB directly.
