### ISSUE TITLE
Only POST request created with no documents returned

### ISSUE THREAD

**Issue by michaelmior** [ArnoSaine/react-pouchdb#5]
I'm trying to use react-pouchdb with a remote server but I can't seem to get any documents to be returned. The query below returns results if used outside React.

```javascript
class Scoreboard extends Component {
  render() {
     return <div>
       {this.props.teams.map(team => (
         <div key={team.id}>{team.name} - {team.score}</div>
       ))}
     </div>
    return <PouchDB name="https://***">
      <Find
        selector={{score: {$gte: null}}}
        sort={[{score: 'desc'}, {name: 'desc'}]}
        render={({docs}) => (
          return docs.map(doc =>
            <div key={doc._id}>{doc.name} - {doc.score}</div>
          )
        )}/>
    </PouchDB>;
  }
}
```

However, all I see in the browser is a POST request to `/scoreboard/index` with the data`{"index":{"fields":["score","name"]},"type":"json"}`.
No `GET` request is ever made to retrieve the documents.
Any idea what I'm missing?

**Comment by ArnoSaine** [comment]
Thank you for reporting the issue.

It was a bug in react-pouchdb. `<Find />` and `<Get />` internally use `withDB`. That caused `db` property incorrectly to be mixed into the `db.find` options.

I fixed this in `0.3.2` and it does not apply to the version `1.0.0-alpha`.

**Comment by michaelmior** [comment]
Thanks! :)

**Comment by michaelmior** [comment]
Thanks! :)
