### ISSUE TITLE
Suspense transition with prop change

### ISSUE THREAD

**Issue by jorbascrumps** [ArnoSaine/react-pouchdb#6]
I've noticed that whenever I update props and `useFind` is called again, there's a short flicker as the fallback UI is rendered. Is it possible to have a smoother transition?

**Comment by ArnoSaine** [comment]
It bothers me too. I don't have any workaround at the moment, but I'm planning to fix it at some point.

**Comment by jorbascrumps** [comment]
Glad I'm not alone! I looked into using [React Transition Group](https://reactcommunity.org/react-transition-group/) but couldn't quite get it to work. If I do eventually, I'll provide an example here.

**Comment by kn0ll** [comment]
@ArnoSaine any thoughts on this in case someone wants to help? :)

**Comment by ArnoSaine** [comment]
@kn0ll Thanks for asking.

I think it's best to wait for the official support for Suspense and data fetching: https://reactjs.org/blog/2018/11/27/react-16-roadmap.html#react-16x-mid-2019-the-one-with-suspense-for-data-fetching

Perhaps there will be an API to render a fallback overlay. If not, it might be possible to create an alternative to `<Suspense>`, which would clone underlaying DOM tree and render that with optional fallback overlay, when some component suspends.

Another option is to add an option for `useFind` and `useGet` to return previous result, until new result is available, but I would keep that as a last resort.

**Comment by ArnoSaine** [comment]
Here's an experimental version of `<Suspense>` that prevents the flickering. If loading takes more than 100 ms, the fallback is shown in a fullscreen overlay.
https://gist.github.com/ArnoSaine/5abf620146435c47563ef280f1a286c2

**Comment by jorbascrumps** [comment]
Sorry @ArnoSaine, just seeing this. Am I correct in assuming this would replace `<Suspense>` components completely? At least until data fetching lands.

**Comment by ArnoSaine** [comment]
@jorbascrumps Yes, exactly.

**Comment by jorbascrumps** [comment]
Great! I'll see if I can get some time to give it a spin. Thank you for taking the time to put this together.

**Comment by ArnoSaine** [comment]
> Here's an experimental version of `<Suspense>` that prevents the flickering. If loading takes more than 100 ms, the fallback is shown in a fullscreen overlay.
> https://gist.github.com/ArnoSaine/5abf620146435c47563ef280f1a286c2

Improved version of this is published here:
https://www.npmjs.com/package/suspense-overlay
